### ISSUE TITLE
Image is not displayed on the screen

### ISSUE THREAD

**Issue by coderboy396** [meghajbhat/Photo-Editor#1]
When i select the image to edit it does not get displayed in the gui screen.

**Comment by meghajbhat** [comment]
Hi @coderboy396 ! You can go ahead and fork this repository to start working on the issue. Once you've made the changes, submit a pull request referencing this issue. Looking forward to your contributions! Let me know if you have any questions or need help.


If you're new to GitHub, here’s a quick overview:
1. Click the "Fork" button at the top-right of this repository to create your own copy.
2. Clone the forked repository to your local machine.
3. Make your changes and commit them.
4. Push the changes to your forked repository.
5. Go back to this repository and click "New Pull Request" to submit your changes.
